---
title: CLARIAH Media Suite
timezone: Europe/Amsterdam
collections:
  posts:
    title: Blog
    output: true
  carousel:
    title: Carousel
    output: false
  faq:
    title: FAQ
    output: true
    permalink: "/documentation/faq/:name"
  glossary:
    title: Glossary
    output: true
    permalink: "/documentation/glossary/:name"
  help:
    title: Help
    output: true
    permalink: "/documentation/:name"
  howtos:
    title: HowTos
    output: true
    permalink: "/documentation/howtos/:name"
  learn:
    title: Learn
    output: true
    permalink: "/learn/:name"
  release-notes:
    title: Release notes
    output: true
    permalink: "/documentation/release-notes/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: blog
- scope:
    path: ''
    type: carousel
  values:
    header: 
    link_txt: 
    link_url: 
- scope:
    path: ''
    type: faq
  values:
    layout: faq
- scope:
    path: ''
    type: glossary
  values:
    layout: glossary
- scope:
    path: ''
    type: release-notes
  values:
    layout: release-notes
- scope:
    path: ''
    type: howtos
  values:
    layout: howtos
- scope:
    path: ''
    type: help
  values:
    layout: help
- scope:
    path: ''
    type: learn
  values:
    layout: tutorial
version: v5.0
email: 
description: 
baseurl: "/mediasuite-website"
url: 
twitter_username: mediasuite_nl
markdown: kramdown
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- script
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
