---
title: CLARIAH Media Suite
timezone: Europe/Amsterdam
collections:
  posts:
    title: Blog
    output: true
  carousel:
    title: Carousel
    output: false
  faq:
    title: FAQ
    output: true
    permalink: "/documentation/faq/:name"
  glossary:
    title: Glossary
    output: true
    permalink: "/documentation/glossary/:name"
  help:
    title: Help
    output: true
    permalink: "/documentation/:name"
  howtos:
    title: HowTos
    output: true
    permalink: "/documentation/howtos/:name"
  labo-help:
    title: Labo help
    output: true
  learn_tutorials_subject:
    title: Learn - Subject tutorials
    output: true
    permalink: "/learn/subject-tutorials/:name"
  learn_tutorials_tool:
    title: Learn - Tool tutorials
    output: true
    permalink: "/learn/tool-tutorials/:name"
  learn_example_projects:
    title: Learn - Example projects
    output: true
    permalink: "/learn/example-projects/:name"
  learn_tool_criticism:
    title: Learn - Tool criticism
    output: true
    permalink: "/learn/tool-criticism/:name"
  release-notes:
    title: Release notes
    output: true
    permalink: "/documentation/release-notes/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: blog
    menu: blog
    permalink: "/blog/:year/:month/:day/:title"
- scope:
    path: ''
    type: carousel
  values:
    header: 
    link_txt: 
    link_url: 
    link_target: 
- scope:
    path: ''
    type: faq
  values:
    layout: faq
    menu: help
- scope:
    path: ''
    type: glossary
  values:
    layout: glossary
    menu: help
- scope:
    path: ''
    type: release-notes
  values:
    layout: release-notes
    menu: help
- scope:
    path: ''
    type: howtos
  values:
    layout: howtos
    menu: help
- scope:
    path: ''
    type: help
  values:
    layout: help
    menu: help
- scope:
    path: ''
    type: learn_tutorials_subject
  values:
    layout: learn_item
    menu: learn
    introduction:
    author: 
    media_type: 
    functionalities: []
    collections: []
    disciplines: []
    version: 
    user_level: 
    user_skills: 
    language: 
    vimeo_url: 
    other_urls: []
    pdf_file: 
- scope:
    path: ''
    type: learn_tutorials_tool
  values:
    layout: learn_item
    menu: learn
    introduction:
    author: 
    media_type: 
    functionalities: []
    collections: []
    disciplines: []
    version: 
    user_level: 
    user_skills: 
    language: 
    vimeo_url: 
    other_urls: []
    pdf_file: 
- scope:
    path: ''
    type: learn_example_projects
  values:
    layout: learn_item
    menu: learn
    introduction:
    author: 
- scope:
    path: ''
    type: learn_tool_criticism
  values:
    layout: learn_item
    menu: learn
    introduction:
    author: 
version: v5.3
url: https://mediasuite.clariah.nl
twitter_username: mediasuite_nl
markdown: kramdown
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- script
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
