---
title: CLARIAH Media Suite
version: v5.0
timezone: Europe/Amsterdam
collections_dir: collections
collections:
  posts:
    title: News
    output: true
    permalink: /blog/:year/:month/:day/:title
  faq:
    title: FAQ
    output: true
    permalink: /documentation/faq/:name
  glossary:
    title: Glossary
    output: true
    permalink: /documentation/glossary/:name
  release-notes:
    title: Release notes
    output: true
    permalink: /documentation/release-notes/:name
  howtos:
    title: Media Suite's HowTos
    output: true
    permalink: /documentation/howtos/:name
  help:
    title: Help
    output: true
    permalink: /documentation/:name
  learn:
    title: Learn
    output: true
    permalink: /learn/:name
  uploads:
    title: Uploads
    output: true
  carousel:
    title: Carousel
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    id: page
    layout: default
- scope:
    path: ''
    type: posts
  values:
    id: blog
    layout: blog
- scope:
    path: ''
    type: faq
  values:
    id: faq
    layout: faq
- scope:
    path: ''
    type: glossary
  values:
    id: glossary
    layout: glossary
- scope:
    path: ''
    type: release-notes
  values:
    id: release-notes
    layout: release-notes
- scope:
    path: ''
    type: howtos
  values:
    id: howtos
    layout: howtos
- scope:
    path: ''
    type: help
  values:
    id: help
    layout: help
- scope:
    path: ''
    type: learn
  values:
    id: learn
    layout: learn
email: 
description: 
baseurl: /mediasuite-website
url: 
twitter_username: mediasuite_nl
markdown: kramdown
plugins:
- jekyll-feed
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- script
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/