---
title: CLARIAH Media Suite
timezone: Europe/Amsterdam
collections_dir: collections
collections:
  posts:
    title: News
    output: true
    permalink: /blog/:year/:month/:day/:title
  faq:
    title: FAQ
    output: true
    permalink: /documentation/faq/:name
  glossary:
    title: Glossary
    output: true
    permalink: /documentation/glossary/:name
  release-notes:
    title: Release notes
    output: true
    permalink: /documentation/release-notes/:name
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    id: page
    layout: default
- scope:
    path: ''
    type: posts
  values:
    id: blog
    layout: blog
- scope:
    path: ''
    type: faq
  values:
    id: faq
    layout: faq
- scope:
    path: ''
    type: glossary
  values:
    id: glossary
    layout: glossary
- scope:
    path: ''
    type: release-notes
  values:
    id: release-notes
    layout: release-notes
#email: bloemendalprijs@beeldengeluid.nl
#description: De Philip Bloemendal Prijs stimuleert jong journalistiek presentatietalent
  # in de media. Genomineerden ontvangen een oorkonde en de winnaar ontvangt tevens
  # een geldbedrag van 3500 euro, te besteden aan een studie- of opleidingsproject om
  # zich binnen het vakgebied verder te bekwamen.
#baseurl: 
#url: https://www.bloemendal.info
twitter_username: mediasuite_nl
markdown: kramdown
plugins:
- jekyll-feed
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- script
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/