name: Deploy branch to mediasuite-acc.rdlabs.beeldengeluid.nl
on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: autodeploy to acc with ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        ansible-playbook mediasuite-website-acc.yml --extra-vars "app_version=${GITHUB_REF##*/}"
