name: Create release from tag
on:
  push:
    tags:
    - '*'

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install jekyll bundler
    - run: bundle exec jekyll build
    - run: tar -cvvzf _site.tar.gz ./_site
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "_site.tar.gz"
        body: "Release ${GITHUB_REF##*/}"

# ENV GEM_HOME="/home/$appuser/gems"
# ENV PATH="/home/$appuser/gems/bin:$PATH"
