name: Deploy Master branch

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: install with ansible
      run: |
        cd /opt/git/rd_infra/scripts/ansible/
        ansible-playbook mediasuite-website.yml
