name: Build main but do not deploy to mediasuite-acc.rdlabs.beeldengeluid.nl
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Update ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        sudo git pull
    - name: build the static files
      run: |
        cd /opt/git/x-omgeving/ansible/
        ansible-playbook mediasuite-website-build.yml
    # - name: autodeploy to acc with ansible
      # run: |
        # cd /opt/git/x-omgeving/ansible/
        # ansible-playbook mediasuite-website-acc.yml
