name: Deploy Master branch

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: autodeploy to tst with ansible
      run: |
        cd /opt/git/rd_infra/scripts/ansible/
        ansible-playbook mediasuite-website-build-test.yml
    - name: autodeploy to acc with ansible
      run: |
        cd /opt/git/rd_infra/scripts/ansible/
        ansible-playbook mediasuite-website-acc.yml
