name: Build login_redirect branch on push, then deploy to both tst and acc
on:
  push:
    branches:
      - login_redirect

jobs:
  build:
    uses: ./.github/workflows/_build-current-branch.yml

  deploy-tst:
    uses: ./.github/workflows/_deploy-branch-to-tst.yml
    needs: [build]

  deploy-acc:
    uses: ./.github/workflows/_deploy-branch-to-acc.yml
    needs: [build]
