name: Build main branch on push, delay deploy until night
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build-current-branch.yml

  release:
    uses: ./.github/workflows/_bump-version-and-release.yml