name: Manual release custom tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Github Tag to create
        required: true
        type: string

jobs:
  release:
    uses: ./.github/workflows/_release-with-built-site-as-artifact.yml
    with:
      tag: ${{inputs.tag}}
