name: Deploy main branch to mediasuite.clariah.nl at night

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Update ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        sudo git pull
    - name: deploy to production with ansible
      run: |
        cd /opt/git/x-omgeving/ansible/
        ansible-playbook mediasuite-website-production.yml
